trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Variables personnalisables
  buildConfiguration: 'Release'  # Configuration de build (Debug, Release, etc.)
  projectName: 'MonProjetNode'  # Nom de votre projet
  outputDirectory: 'dist'  # Répertoire de sortie de la build
  azureSubscription: 'VotreAbonnementAzure'  # Nom de votre abonnement Azure
  appService: 'MonAppService'  # Nom de votre App Service

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Spécifiez la version Node.js souhaitée
  displayName: 'Installer Node.js'

- task: npm@1
  inputs:
    command: custom
    customCommand: 'start'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Installer les dépendances et exécuter la build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(outputDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publier les artefacts'



# Tâches optionnelles :
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.js'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/coverage'
    Overwrite: true
  displayName: 'Copier les fichiers de couverture de code'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/coverage/*.xml'
    testRunTitle: 'Tests unitaires'
  displayName: 'Publier les résultats des tests'
